[package]
name = "convolution"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
complex = { package = "complex", path = "../complex" }
modint = { package = "modint", path = "../modint" }
numeric = { package = "numeric", path = "../numeric" }

[dev-dependencies]
iolib = { package = "iolib", path = "../iolib" }
proconio = { version = "0.3.6", features = ["derive"] }
