[package]
name = "tayu-procon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.1"
proconio = "0.4.3"
rand = "0.8.5"

[[example]]
name = "io"
