[package]
name = "rational"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zero-one = { package = "numeric", git = "https://github.com/tayu0110/tayu-procon.git" }
