[package]
name = "balanced-bst"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
iolib = { path = "../iolib" }
rand = "0.8.5"
