[package]
name = "ds"
version = "0.1.0"
edition = "2021"
license = "CC0-1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
iolib = { path = "../iolib" }
proconio = "0.4.5"
rand = "0.8.5"

[features]
default = ["full"]
full = ["fixed-ring-queue", "btree-multiset", "double-ended-priority-queue"]
fixed-ring-queue = []
btree-multiset = []
double-ended-priority-queue = []
